print("Welcome to Python Calculator")
num1=float(input('Enter the num 1 :'))
num2=float(input('Enter the num 2 :'))
print("1. Addition(+)")
print("2. Substration(-)")
print("3. Multiplication(*)")
print("4. Division(/)")
print("5. Exponetial(**)")
print("6. Modulus(%)")
choice=int(input('Enter the no. 1-6: '))